name: EasyBan
main: uk.org.whoami.easyban.EasyBan
version: 1.4
commands:
    ekick:
        description: Kick player
        usage: /ekick playername
    ehistory:
        description: List all ips of a player
        usage: /elistips playername
    ealternative:
        description: Get alternative nicknames of a player
        usage: /ealternative playername
    eban:
        description: Ban player
        usage: /eban playername [reason] [time]
    eunban:
        description: Unban player
        usage: /eunban playername
    ebaninfo:
        description: Get informations about a ban
        usage: /ebaninfo playername/subnet
    elistbans:
        description: List all banned players
        usage: /elistbans
    elisttmpbans:
        description: List all temporary bans
        usage: /elisttmpbans
    ebansubnet:
        description: Ban a whole subnet
        usage: /esubnetban a.b.c.d/w.x.y.z [reason]
    eunbansubnet:
        description: Unban a whole subnet
        usage: /esubnetunban a.b.c.d/w.x.y.z
    elistsubnets:
        description: List all banned subnets
        usage: /elistsubnets
    ebancountry:
        description: Ban a country
        usage: /ebancountry countrycode
    eunbancountry:
        description: Unban a country
        usage: /eunbancountry countrycode
    elistcountries:
        description: Show all banned countries
        usage: /elistcountries
    ewhitelist:
        description: Whitelist players from range bans
        usage: /ewhitelist playername
    eunwhitelist:
        description: Unwhitelist a player
        usage: /eunwhitelist playername
    elistwhite:
        description: Show whitelisted players
        usage: /elistwhite