name: EasyBan
main: uk.org.whoami.easyban.EasyBan
version: 0.2
commands:
    ekick:
        description: Kick player
        usage: /ekick playername
    eban:
        description: Ban player
        usage: /eban playername
    eunban:
        description: Unban player
        usage: /eunban playername
    esubnetban:
        description: Ban a whole Subnet
        usage: /esubnetban a.b.c.d/w.x.y.z
    esubnetunban:
        description: Unban a whole Subnet
        usage: /esubnetunban a.b.c.d/w.x.y.z